const GET_TODOS = 'GET_TODOS'
const ADD_TODO = 'ADD_TODO'
const SET_ALL_TODOS = 'SET_TODOS'
const SET_DONE_TODOS = 'SET_DONE_TODOS'
const SET_UNDONE_TODOS = 'SET_UNDONE_TODOS'
const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS'
const DELETE_TODO_BY_ID = 'DELETE_TODO_BY_ID'
const TOGGLE_TODO = 'TOGGLE_TODO'
const UPDATE_TITLE_TODO = 'UPDATE_TITLE_TODO'


export {
    GET_TODOS,
    SET_ALL_TODOS,
    SET_DONE_TODOS,
    SET_UNDONE_TODOS,
    DELETE_ALL_TODOS,
    DELETE_TODO_BY_ID,
    TOGGLE_TODO,
    UPDATE_TITLE_TODO,
    ADD_TODO,
}